theme: databio

site_name: PEPPRO
site_author: Jason Smith
site_url: http://code.databio.org/PEPPRO/
site_logo: img/peppro_logo_white.svg
repo_url: https://github.com/databio/peppro/
#google_analytics: ['UA-127092878-1', 'code.databio.org/PEPPRO']

markdown_extensions:
  - fontawesome_markdown  # pip install --user fontawesome-markdown
  - pymdownx.details  # pip install --user pymdown-extensions

nav:
  - Getting Started:
    - Introduction: 'README.md'
 #   - Features: 'features.md'
    - Install and run: 'install.md'
 #   - Extended tutorial: 'tutorial.md'
  - How-to Guides:
 #   - How to configure reference genome assemblies: 'howto/install-refgenie.md'
 #   - How to download SRA data: 'howto/download.md'
    - How to download or create annotation files: 'howto/annotation-files.md'
 #   - How to run multiple samples using looper: 'howto/run-looper.md'
 #   - How to run the pipeline on a cluster: 'howto/run-cluster.md'
 #   - How to run the pipeline in a container: 'howto/use-container.md'
 # - Reference: 
 #   - Example output file structure: 'browse_output.md'
 #   - "Example summary: gold project": 'files/examples/gold/summary.html'
 #   - "Example summary: tutorial project": 'files/examples/tutorial/tutorial_summary.html'
    - Usage: 'usage.md'
 #   - FAQ: faq.md
 #   - Glossary: 'glossary.md'
    - Changelog: changelog.md
 #   - Support: contact.md

plugins:
  - search
  - databio:
      autodoc_modules: null
      autodoc_build: "docs_build"
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"$CODEBASE/databio/peppro/pipelines/peppro.py --help

navbar:
  right:
  - text: Software & Data
    icon: fa-code fa-lg
    href: http://databio.org/software/
  # - text: Contact us
  #   icon: fa-envelope
  #   href: contact
