theme: databio

site_name: peppro
site_author: Jason Smith
site_url: http://peppro.databio.org/
site_logo: img/peppro_logo_gray.svg
repo_url: https://github.com/databio/peppro/
#google_analytics: ['UA-127092878-1', 'code.databio.org/peppro']

markdown_extensions:
  - fontawesome_markdown  # pip install --user fontawesome-markdown
  - pymdownx.details  # pip install --user pymdown-extensions

nav:
  - Getting Started:
    - Introduction: 'README.md'
    - Features: 'features.md'
    - Install and run: 'install.md'
    - Extended tutorial: 'tutorial.md'
  - How-to Guides:
    - Run PEPPRO directly: 'run_direct.md'
    - Run PEPPRO in containers: 'use_container.md'
    - Configuring prealignments: 'prealignments.md'
    - Configuring computing: 'configure_compute.md'
    - Detailed install guide: 'detailed_install.md'
    - Annotation files: 'annotation.md'
  - Reference: 
    - FAQ: 'faq.md'
    - Usage: 'usage.md'
    - Advanced container reference: 'container_reference.md'
    - Changelog: 'changelog.md'
    - Support: 'https://github.com/databio/peppro/issues'
    - Example output file structure: 'browse_output.md'
    - "Example summary: tutorial project": 'files/examples/tutorial/tutorial_summary.html'

plugins:
  - search
  - databio:
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"$CODEBASE/databio/peppro/pipelines/peppro.py --help

navbar:
  right:
  - text: Software & Data
    icon: fa-code fa-lg
    href: http://databio.org/software/
