theme: databio

site_name: PEPPRO
site_author: Jason Smith
site_url: http://code.databio.org/PEPPRO/
site_logo: img/peppro_logo_white.svg
repo_url: https://github.com/databio/peppro/
#google_analytics: ['UA-127092878-1', 'code.databio.org/PEPPRO']

markdown_extensions:
  - fontawesome_markdown  # pip install --user fontawesome-markdown
  - pymdownx.details  # pip install --user pymdown-extensions

nav:
  - Getting Started:
    - Introduction: 'README.md'
    - Features: 'features.md'
    - Install and run: 'install.md'
  - How-to Guides:
    - Annotation files: 'howto/annotation_files/'
  - Reference: 
    - Usage: 'usage.md'
    - Changelog: changelog.md

plugins:
  - search
  - databio:
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"$CODEBASE/databio/peppro/pipelines/peppro.py --help

navbar:
  right:
  - text: Software & Data
    icon: fa-code fa-lg
    href: http://databio.org/software/
