protocol_mapping:
  PRO: peppro.py
  pro: peppro.py
  PRO-SEQ: peppro.py
  PRO-seq: peppro.py
  PROSEQ: peppro.py
  proseq: peppro.py

pipelines:
  peppro.py:
    name: PEPPRO
    path: pipelines/peppro.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": read1
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--runon": runon
      "--adapter": adapter
      "--dedup": dedup
      "--trimmer": trimmer
      "--umi": umi
      "--umi_len": umi_len
      "--max_len": max_len
      "--scale": scale
      "--parts": parts
      "--prealignments": prealignments
      "--TSS-name": TSS_name
      "--pre-name": pre_name
      "--anno-name": anno_name
      "--keep": keep
      "--noFIFO": no_fifo
      "--complexity": complexity
    compute:
      singularity_image: ${SIMAGES}peppro
      docker_image: databio/peppro
    summarizers:

    summary_results:

    resources:
      default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "0-12:00:00"


