protocol_mapping:
  PRO: peppro
  pro: peppro
  GRO: peppro
  gro: peppro
  PRO-SEQ: peppro
  PRO-seq: peppro
  PROSEQ: peppro
  proseq: peppro
  groseq: peppro
  GROSEQ: peppro
  GRO-SEQ: peppro
  GRO-seq: peppro

pipelines:
  peppro:
    name: PEPPRO
    path: pipelines/peppro.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": read1
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--protocol": protocol
      "--adapter-tool": adapter
      "--dedup-tool": dedup
      "--trimmer-tool": trimmer
      "--umi-len": umi_len
      "--max-len": max_len
      "--sob": sob
      "--scale": scale
      "--prealignments": prealignments
      "--TSS-name": TSS_name
      "--pre-name": pre_name
      "--anno-name": anno_name
      "--search-file": search_file
      "--coverage": coverage
      "--keep": keep
      "--noFIFO": no_fifo
      "--complexity": complexity
    compute:
      singularity_image: ${SIMAGES}peppro
      docker_image: databio/peppro
      bulker_crate: peppro
    outputs:
      cutadapt_report: "cutadapt/{sample.sample_name}_cutadapt.txt"
      plus_bw: "signal_{sample.genome}/{sample.sample_name}_plus_body_0-mer.bw"
      minus_bw: "signal_{sample.genome}/{sample.sample_name}_minus_body_0-mer.bw"
      plus_bam: "aligned_{sample.genome}/{sample.sample_name}_plus.bam"
      minus_bam: "aligned_{sample.genome}/{sample.sample_name}_minus.bam"
      gene_counts_bed: "signal_{sample.genome}/{sample.sample_name}_gene_coverage.bed"
      pause_indicies_bed: "QC_{sample.genome}/{sample.sample_name}_pause_index.bed.gz"
      mrna_contamination_bed: "QC_{sample.genome}/{sample.sample_name}_exon_intron_ratios.bed.gz"
    summarizers:
      - tools/PEPPRO_complexity_curves.R
      - tools/PEPPRO_counts.R
    bioconductor:
      readFunName: readPepproGeneCounts
      readFunPath: BiocProject/readPepproGeneCounts.R
    summary_results:
      - library_complexity_file:
        caption: "Library complexity file"
        description: "Plots each sample's library complexity on a single plot."
        thumbnail_path: "summary/{name}_libComplexity.png"
        path: "summary/{name}_libComplexity.pdf"
    resources:
      default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "00-18:00:00"
      femto:
        file_size: "0.001"
        cores: "1"
        mem: "8000"
        time: "00-04:00:00"
      pico:
        file_size: "0.05"
        cores: "2"
        mem: "12000"
        time: "00-08:00:00"
      nano:
        file_size: "0.5"
        cores: "4"
        mem: "16000"
        time: "00-12:00:00"
      micro:
        file_size: "1"
        cores: "8"
        mem: "16000"
        time: "00-24:00:00"
      milli:
        file_size: "10"
        cores: "16"
        mem: "32000"
        time: "02-00:00:00"


