protocol_mapping:
  PRO: peppro.py
  PRO-SEQ: peppro.py 

pipelines:
  peppro.py:
    name: PEPPRO
    path: pipelines/peppro.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": read1
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--prealignments": prealignments
      "--adapter": adapter
      "--dedup": dedup
      "--trimmer": trimmer
      "--keep": keep
      "--noFIFO": no_fifo
    compute:
      singularity_image: ${SIMAGES}peppro
      docker_image: databio/peppro
    summarizers:

    summary_results:

    resources:
      default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "0-12:00:00"


