protocol_mapping:
  PRO: peppro
  pro: peppro
  PRO-SEQ: peppro
  PRO-seq: peppro
  PROSEQ: peppro
  proseq: peppro

pipelines:
  peppro:
    name: PEPPRO
    path: pipelines/peppro.py
    looper_args: True
    required_input_files: [read1]
    all_input_files: [read1, read2]
    ngs_input_files: [read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": read1
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--runon": runon
      "--adapter": adapter
      "--dedup": dedup
      "--trimmer": trimmer
      "--umi": umi
      "--umi_len": umi_len
      "--max_len": max_len
      "--sob": sob
      "--scale": scale
      "--parts": parts
      "--prealignments": prealignments
      "--TSS-name": TSS_name
      "--pre-name": pre_name
      "--anno-name": anno_name
      "--coverage": coverage
      "--keep": keep
      "--noFIFO": no_fifo
      "--complexity": complexity
    compute:
      singularity_image: ${SIMAGES}peppro
      docker_image: databio/peppro
    summarizers:
      - tools/PEPPRO_summarizer.R
    summary_results:
      - library_complexity_file:
        caption: "Library complexity file"
        description: "Plots each sample's library complexity on a single plot."
        thumbnail_path: "summary/{name}_libComplexity.png"
        path: "summary/{name}_libComplexity.pdf"
    resources:
      default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "00-18:00:00"
      femto:
        file_size: "0.001"
        cores: "1"
        mem: "8000"
        time: "00-04:00:00"
      pico:
        file_size: "0.05"
        cores: "2"
        mem: "12000"
        time: "00-08:00:00"
      nano:
        file_size: "0.5"
        cores: "4"
        mem: "16000"
        time: "00-12:00:00"
      micro:
        file_size: "1"
        cores: "8"
        mem: "16000"
        time: "00-24:00:00"
      milli:
        file_size: "10"
        cores: "16"
        mem: "32000"
        time: "02-00:00:00"


